### ISSUE TITLE
OpenAL error when ending level

### ISSUE THREAD

**Issue by angelusmetal** [angelusmetal/dungeon#139]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Unable to allocate audio buffers. AL Error: 40963
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.play(OpenALMusic.java:78)
	at com.dungeon.engine.audio.AudioManager.playMusic(AudioManager.java:67)
	at com.dungeon.engine.audio.AudioManager.playMusic(AudioManager.java:31)
	at com.dungeon.game.Dungeon.lambda$render$135(Dungeon.java:181)
	at com.dungeon.game.render.effect.FadeEffect.dispose(FadeEffect.java:58)
	at com.dungeon.engine.entity.repository.Repository.update(Repository.java:26)
	at com.dungeon.game.Dungeon.render(Dungeon.java:170)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by angelusmetal** [comment]
Fixed on d329a1eeb5b476df1cce36dd709e0b0bb7d1433f
